// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: interface/cap.proto

package cap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapData int32

const (
	CapData_TIM CapData = 0
	CapData_MET CapData = 1
	CapData_BEL CapData = 2
	CapData_PVC CapData = 3
	CapData_PVD CapData = 4
)

// Enum value maps for CapData.
var (
	CapData_name = map[int32]string{
		0: "TIM",
		1: "MET",
		2: "BEL",
		3: "PVC",
		4: "PVD",
	}
	CapData_value = map[string]int32{
		"TIM": 0,
		"MET": 1,
		"BEL": 2,
		"PVC": 3,
		"PVD": 4,
	}
)

func (x CapData) Enum() *CapData {
	p := new(CapData)
	*p = x
	return p
}

func (x CapData) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapData) Descriptor() protoreflect.EnumDescriptor {
	return file_interface_cap_proto_enumTypes[0].Descriptor()
}

func (CapData) Type() protoreflect.EnumType {
	return &file_interface_cap_proto_enumTypes[0]
}

func (x CapData) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapData.Descriptor instead.
func (CapData) EnumDescriptor() ([]byte, []int) {
	return file_interface_cap_proto_rawDescGZIP(), []int{0}
}

type Cap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Onl bool      `protobuf:"varint,1,opt,name=onl,proto3" json:"onl,omitempty"`
	Dev string    `protobuf:"bytes,2,opt,name=dev,proto3" json:"dev,omitempty"`
	Acc []CapData `protobuf:"varint,3,rep,packed,name=acc,proto3,enum=iot_service.CapData" json:"acc,omitempty"`
}

func (x *Cap) Reset() {
	*x = Cap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_cap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cap) ProtoMessage() {}

func (x *Cap) ProtoReflect() protoreflect.Message {
	mi := &file_interface_cap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cap.ProtoReflect.Descriptor instead.
func (*Cap) Descriptor() ([]byte, []int) {
	return file_interface_cap_proto_rawDescGZIP(), []int{0}
}

func (x *Cap) GetOnl() bool {
	if x != nil {
		return x.Onl
	}
	return false
}

func (x *Cap) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *Cap) GetAcc() []CapData {
	if x != nil {
		return x.Acc
	}
	return nil
}

var File_interface_cap_proto protoreflect.FileDescriptor

var file_interface_cap_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6f, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x51, 0x0a, 0x03, 0x43, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6f, 0x6e, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x76, 0x12, 0x26, 0x0a,
	0x03, 0x61, 0x63, 0x63, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x69, 0x6f, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x03, 0x61, 0x63, 0x63, 0x2a, 0x36, 0x0a, 0x07, 0x43, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x49, 0x4d, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x45, 0x54,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50,
	0x56, 0x43, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x56, 0x44, 0x10, 0x04, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x78, 0x69,
	0x63, 0x7a, 0x2f, 0x69, 0x6f, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63,
	0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interface_cap_proto_rawDescOnce sync.Once
	file_interface_cap_proto_rawDescData = file_interface_cap_proto_rawDesc
)

func file_interface_cap_proto_rawDescGZIP() []byte {
	file_interface_cap_proto_rawDescOnce.Do(func() {
		file_interface_cap_proto_rawDescData = protoimpl.X.CompressGZIP(file_interface_cap_proto_rawDescData)
	})
	return file_interface_cap_proto_rawDescData
}

var file_interface_cap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interface_cap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_interface_cap_proto_goTypes = []interface{}{
	(CapData)(0), // 0: iot_service.CapData
	(*Cap)(nil),  // 1: iot_service.Cap
}
var file_interface_cap_proto_depIdxs = []int32{
	0, // 0: iot_service.Cap.acc:type_name -> iot_service.CapData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interface_cap_proto_init() }
func file_interface_cap_proto_init() {
	if File_interface_cap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interface_cap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interface_cap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interface_cap_proto_goTypes,
		DependencyIndexes: file_interface_cap_proto_depIdxs,
		EnumInfos:         file_interface_cap_proto_enumTypes,
		MessageInfos:      file_interface_cap_proto_msgTypes,
	}.Build()
	File_interface_cap_proto = out.File
	file_interface_cap_proto_rawDesc = nil
	file_interface_cap_proto_goTypes = nil
	file_interface_cap_proto_depIdxs = nil
}
